# NB: во всех сервисах прописана инструкция
# env_file:
#   - ${ENV_PATH:-.env}
#, поэтому ENV_PATH должна быть определёна
# во всех используемых через --env-file файлах

x-controller-resources:
  &controller-resources
  resources:
    limits:
      # cpus: '${CONTROLLER_LIMIT_CPUS}'
      memory: ${CONTROLLER_LIMIT_MEMORY}
    reservations:
      cpus: '${CONTROLLER_RESERVE_CPUS}'
      memory: ${CONTROLLER_RESERVE_MEMORY}

x-broker-resources:
  &broker-resources
  resources:
    limits:
      # cpus: '${BROKER_LIMIT_CPUS}'
      memory: ${BROKER_LIMIT_MEMORY}
    reservations:
      cpus: '${BROKER_RESERVE_CPUS}'
      memory: ${BROKER_RESERVE_MEMORY}

x-stage-quorum-voters:
  &stage-quorum-voters
  KAFKA_CONTROLLER_QUORUM_VOTERS: "\
    ${SC_1_NODE_ID}@${SC_1_NAME}:${SC_1_PORT_90},\
    ${SC_2_NODE_ID}@${SC_2_NAME}:${SC_2_PORT_90},\
    ${SC_3_NODE_ID}@${SC_3_NAME}:${SC_3_PORT_90}"

x-mart-quorum-voters:
  &mart-quorum-voters
  KAFKA_CONTROLLER_QUORUM_VOTERS: "\
    ${MC_1_NODE_ID}@${MC_1_NAME}:${MC_1_PORT_90},\
    ${MC_2_NODE_ID}@${MC_2_NAME}:${MC_2_PORT_90},\
    ${MC_3_NODE_ID}@${MC_3_NAME}:${MC_3_PORT_90}"

# общие переменные окружения для всех нод-контроллеров

x-kafka_controller:
  &kafka_controller-env
  KAFKA_PROCESS_ROLES: controller
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_SSL,INTERNAL:SASL_SSL
  KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  # в след. строке можно на время разработки выставить true просто для удобства демо-проекта
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
  KAFKA_AUTO_LEADER_REBALANCE_ENABLE: true
  KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: false
  KAFKA_REPLICATION_QUOTA_WINDOW_NUM: 11
  KAFKA_REPLICATION_QUOTA_WINDOW_SIZE_SECONDS: 1
  KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/controller.sasl.jaas.conf"
  # для отладки SSL
  # KAFKA_OPTS: "-Djavax.net.debug=ssl,handshake"
  # KAFKA_LISTENER_NAME_CONTROLLER_SASL_JAAS_CONFIG_NAME: "ControllerServer"

  # SSL Config
  KAFKA_SSL_SECRETS_DIR: /etc/kafka/secrets
  KAFKA_SSL_TRUSTSTORE_LOCATION: ${CONTAINER_PATH_TRUSTSTORE}
  KAFKA_SSL_KEYSTORE_TYPE: ${KEYSTORE_TYPE}
  KAFKA_SSL_KEYSTORE_LOCATION: ${CONTAINER_PATH_KEYSTORE}
  # креды указываем через _PASSWORD, через _CREDENTIALS не хочет
  KAFKA_SSL_TRUSTSTORE_PASSWORD: ${KAFKA_TRUSTSTORE_CREDS}
  KAFKA_SSL_KEYSTORE_PASSWORD: ${KAFKA_KEYSTORE_CREDS}
  KAFKA_SSL_KEY_PASSWORD: ${KAFKA_SSLKEY_CREDS}
  KAFKA_SSL_CLIENT_AUTH: required

  # SASL Config
  KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
  KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
  KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
  KAFKA_SECURITY_PROTOCOL: 'SASL_SSL'

  # ACL Config
  KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
  KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: false
  KAFKA_SUPER_USERS: User:${SASL_UNAME_ADMIN};User:${SASL_UNAME_KAFKA_CONTROLLER};User:${SASL_UNAME_KAFKA_BROKER} # ;User:${SASL_UNAME_SCHEMA_REGISTRY}

x-controller-entry-write-secrets:
  &controller-entrypoint-with-secrets
    user: root
    entrypoint:
      - /bin/sh
      - -c
      - |
        cat <<EOF > /etc/kafka/secrets/controller.sasl.jaas.conf
        controller.KafkaServer {
            org.apache.kafka.common.security.plain.PlainLoginModule required
            username="${SASL_UNAME_KAFKA_CONTROLLER}"
            password="${SASL_PWD_KAFKA_CONTROLLER}"
            user_${SASL_UNAME_KAFKA_CONTROLLER}="${SASL_PWD_KAFKA_CONTROLLER}"
            user_${SASL_UNAME_KAFKA_BROKER}="${SASL_PWD_KAFKA_BROKER}"
            user_${SASL_UNAME_ADMIN}="${SASL_PWD_ADMIN}";
        };
        EOF

        cat <<EOF > /etc/kafka/secrets/admin-client.properties
        security.protocol=SASL_SSL
        sasl.mechanism=PLAIN
        sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
            username="${SASL_UNAME_ADMIN}" \
            password="${SASL_PWD_ADMIN}";

        ssl.truststore.location=${CONTAINER_PATH_TRUSTSTORE}
        ssl.truststore.password=${KAFKA_TRUSTSTORE_CREDS}

        ssl.keystore.location=${CONTAINER_PATH_KEYSTORE}
        ssl.keystore.password=${KAFKA_KEYSTORE_CREDS}
        ssl.key.password=${KAFKA_SSLKEY_CREDS}
        EOF

        # Права для пользователя 1000 (appuser в Ubuntu)
        # chown 1000 + chmod 600 - не надо,
        # надо без chown и chmod 664
        # (возможно потому, что мы в vulume на одну и ту же диру
        # хостовой машины, но на два образа с двумя разными юзерами,
        # от которых приложение в контейнере зпускается)
        #chown 1000:1000 /etc/kafka/secrets/controller.sasl.jaas.conf
        #chmod 600 /etc/kafka/secrets/controller.sasl.jaas.conf
        chmod 664 /etc/kafka/secrets/controller.sasl.jaas.conf
        chmod 664 /etc/kafka/secrets/admin-client.properties

        echo "JAAS and admin-client.properties for Controller generated from .env"
        exec su -s /bin/sh -c '/etc/confluent/docker/run' appuser

# общие переменные окружения для всех нод-брокеров
x-kafka_broker:
  &kafka_broker-env
  KAFKA_PROCESS_ROLES: broker

  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
  #KAFKA_TRANSACTION_STATE_LOG_NUM_PARTITIONS: ${TRANSACTION_STATE_PARTITIONS}
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  #KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: ${TRANSACTION_STATE_PARTITIONS}
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  KAFKA_TRANSACTIONAL_ID_EXPIRATION_MS: 604800000
  KAFKA_TRANSACTION_PARTITION_VERIFICATION_ENABLE: "false"
  KAFKA_PRODUCER_ID_EXPIRATION_MS: 86400000

  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:SASL_SSL,CONTROLLER:SASL_SSL,INTERNAL:SASL_SSL
  KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  # в след. строке можно на время разработки выставить true просто для удобства демо-проекта
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
  KAFKA_AUTO_LEADER_REBALANCE_ENABLE: true
  KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: false
  KAFKA_REPLICATION_QUOTA_WINDOW_NUM: 11
  KAFKA_REPLICATION_QUOTA_WINDOW_SIZE_SECONDS: 1
  KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/broker.sasl.jaas.conf"
  # для отладки SSL
  # KAFKA_OPTS: "-Djavax.net.debug=ssl,handshake"
  # KAFKA_LISTENER_NAME_INTERNAL_SASL_JAAS_CONFIG_NAME: "KafkaServer"

  # SSL Config
  KAFKA_SSL_SECRETS_DIR: /etc/kafka/secrets
  KAFKA_SSL_TRUSTSTORE_LOCATION: ${CONTAINER_PATH_TRUSTSTORE}
  KAFKA_SSL_KEYSTORE_TYPE: ${KEYSTORE_TYPE}
  KAFKA_SSL_KEYSTORE_LOCATION: ${CONTAINER_PATH_KEYSTORE}
  # креды указываем через _PASSWORD, через _CREDENTIALS не хочет
  KAFKA_SSL_TRUSTSTORE_PASSWORD: ${KAFKA_TRUSTSTORE_CREDS}
  KAFKA_SSL_KEYSTORE_PASSWORD: ${KAFKA_KEYSTORE_CREDS}
  KAFKA_SSL_KEY_PASSWORD: ${KAFKA_SSLKEY_CREDS}
  KAFKA_SSL_CLIENT_AUTH: required

  # SASL Config
  KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
  KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
  KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
  KAFKA_SECURITY_PROTOCOL: 'SASL_SSL'

  # ACL Config
  KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
  KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: false
  KAFKA_SUPER_USERS: User:${SASL_UNAME_ADMIN};User:${SASL_UNAME_KAFKA_CONTROLLER};User:${SASL_UNAME_KAFKA_BROKER} # ;User:${SASL_UNAME_SCHEMA_REGISTRY}

x-broker-entry-write-secrets:
  &broker-entrypoint-with-secrets
    user: root
    entrypoint: 
      - /bin/sh
      - -c
      - |
        cat <<EOF > /etc/kafka/secrets/broker.sasl.jaas.conf
        KafkaServer {
            org.apache.kafka.common.security.plain.PlainLoginModule required
            username="${SASL_UNAME_KAFKA_BROKER}"
            password="${SASL_PWD_KAFKA_BROKER}"
            user_${SASL_UNAME_ADMIN}="${SASL_PWD_ADMIN}"
            user_${SASL_UNAME_KAFKA_CONTROLLER}="${SASL_PWD_KAFKA_CONTROLLER}"
            user_${SASL_UNAME_KAFKA_BROKER}="${SASL_PWD_KAFKA_BROKER}"
            user_${SASL_UNAME_KAFKA_UI}="${SASL_PWD_KAFKA_UI}"
            user_${SASL_UNAME_KAFKA_CONNECT}="${SASL_PWD_KAFKA_CONNECT}"
            user_${SASL_UNAME_KAFKA_CONNECT}="${SASL_PWD_KAFKA_CONNECT}"
            user_${SASL_UNAME_PRODUCER}="${SASL_PWD_PRODUCER}"
            user_${SASL_UNAME_SCHEMA_REGISTRY}="${SASL_PWD_SCHEMA_REGISTRY}";
        };
        EOF

        cat <<EOF > /etc/kafka/secrets/admin-client.properties
        security.protocol=SASL_SSL
        sasl.mechanism=PLAIN
        sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
            username="${SASL_UNAME_ADMIN}" \
            password="${SASL_PWD_ADMIN}";

        ssl.truststore.location=${CONTAINER_PATH_TRUSTSTORE}
        ssl.truststore.password=${KAFKA_TRUSTSTORE_CREDS}

        ssl.keystore.location=${CONTAINER_PATH_KEYSTORE}
        ssl.keystore.password=${KAFKA_KEYSTORE_CREDS}
        ssl.key.password=${KAFKA_SSLKEY_CREDS}

        # Игнорировать проверку имени хоста
        # ssl.endpoint.identification.algorithm=
        EOF

        # Права для пользователя 1000 (appuser в Ubuntu)
        # chown 1000 + chmod 600 - не надо,
        # надо без chown и chmod 664
        # (возможно потому, что мы в vulume на одну и ту же диру
        # хостовой машины, но на два образа с двумя разными юзерами,
        # от которых приложение в контейнере зпускается)
        #chown 1000:1000 /etc/kafka/secrets/broker.sasl.jaas.conf
        #chmod 600 /etc/kafka/secrets/broker.sasl.jaas.conf
        chmod 664 /etc/kafka/secrets/broker.sasl.jaas.conf
        chmod 664 /etc/kafka/secrets/admin-client.properties

        echo "JAAS and admin-client.properties for Broker generated from .env"
        exec su -s /bin/sh -c '/etc/confluent/docker/run' appuser

services:

# kafka-stage-cluster, kafka-mart-cluster
# SC_ = STAGE_CONTROLLER_
# MC_ = MART_CONTROLLER_
# SB_ = STAGE_BROKER_
# MB_ = MART_BROKER_

# kafka stage cluster: KRaft, 3 controllers, 3 brokers

  # stage cluster controllers

  # stage controller 1/3
  stage-controller-1:
    image: ${IMAGE}
    container_name: ${SC_1_NAME}
    hostname: ${SC_1_NAME}
    env_file:
      - ${ENV_PATH:-.env}
    ports:
      - ${SC_1_PORT_90}:${SC_1_PORT_90}
      - ${SC_1_PORT_91}:${SC_1_PORT_91}
    environment:
      <<: [*kafka_controller-env, *stage-quorum-voters]

      CLUSTER_ID: ${CLUSTER_ID_STAGE}
      KAFKA_NODE_ID: ${SC_1_NODE_ID}
      KAFKA_LISTENERS: CONTROLLER://:${SC_1_PORT_90}

    volumes:
      - ./etc-kafka-secrets:/etc/kafka/secrets
      - ${SC_1_NAME}_data:/var/lib/kafka/data
    networks:
      - ${STAGE_CLUSTER_NETWORK}
    <<: *controller-entrypoint-with-secrets
    deploy:
      <<: *controller-resources

  # stage controller 2/3
  stage-controller-2:
    image: ${IMAGE}
    container_name: ${SC_2_NAME}
    hostname: ${SC_2_NAME}
    env_file:
      - ${ENV_PATH:-.env}
    ports:
      - ${SC_2_PORT_90}:${SC_2_PORT_90}
      - ${SC_2_PORT_91}:${SC_2_PORT_91}
    environment:
      <<: [*kafka_controller-env, *stage-quorum-voters]

      CLUSTER_ID: ${CLUSTER_ID_STAGE}
      KAFKA_NODE_ID: ${SC_2_NODE_ID}
      KAFKA_LISTENERS: CONTROLLER://:${SC_2_PORT_90}

    volumes:
      - ./etc-kafka-secrets:/etc/kafka/secrets
      - ${SC_2_NAME}_data:/var/lib/kafka/data
    networks:
      - ${STAGE_CLUSTER_NETWORK}
    <<: *controller-entrypoint-with-secrets
    deploy:
      <<: *controller-resources

  # stage controller 3/3
  stage-controller-3:
    image: ${IMAGE}
    container_name: ${SC_3_NAME}
    hostname: ${SC_3_NAME}
    env_file:
      - ${ENV_PATH:-.env}
    ports:
      - ${SC_3_PORT_90}:${SC_3_PORT_90}
      - ${SC_3_PORT_91}:${SC_3_PORT_91}
    environment:
      <<: [*kafka_controller-env, *stage-quorum-voters]

      CLUSTER_ID: ${CLUSTER_ID_STAGE}
      KAFKA_NODE_ID: ${SC_3_NODE_ID}
      KAFKA_LISTENERS: CONTROLLER://:${SC_3_PORT_90}

    volumes:
      - ./etc-kafka-secrets:/etc/kafka/secrets
      - ${SC_3_NAME}_data:/var/lib/kafka/data
    networks:
      - ${STAGE_CLUSTER_NETWORK}
    <<: *controller-entrypoint-with-secrets
    deploy:
      <<: *controller-resources

  # stage cluster brokers

  # stage broker 1/3
  stage-broker-1:
    image: ${IMAGE}
    container_name: ${SB_1_NAME}
    hostname: ${SB_1_NAME}
    env_file:
      - ${ENV_PATH:-.env}
    ports:
      - ${SB_1_PORT_90}:${SB_1_PORT_90}
      - ${SB_1_PORT_91}:${SB_1_PORT_91}
    environment:
      <<: [*kafka_broker-env, *stage-quorum-voters]

      CLUSTER_ID: ${CLUSTER_ID_STAGE}
      KAFKA_NODE_ID: ${SB_1_NODE_ID}
      KAFKA_LISTENERS: BROKER://:${SB_1_PORT_90},INTERNAL://:${SB_1_PORT_92}
      KAFKA_ADVERTISED_LISTENERS: BROKER://localhost:${SB_1_PORT_90},INTERNAL://${SB_1_NAME}:${SB_1_PORT_92}

    volumes:
      - ./etc-kafka-secrets:/etc/kafka/secrets
      - ${SB_1_NAME}_data:/var/lib/kafka/data
    networks:
      - ${STAGE_CLUSTER_NETWORK}
    <<: *broker-entrypoint-with-secrets
    deploy:
      <<: *broker-resources

  # stage broker 2/3
  stage-broker-2:
    image: ${IMAGE}
    container_name: ${SB_2_NAME}
    hostname: ${SB_2_NAME}
    env_file:
      - ${ENV_PATH:-.env}
    ports:
      - ${SB_2_PORT_90}:${SB_2_PORT_90}
      - ${SB_2_PORT_91}:${SB_2_PORT_91}
    environment:
      <<: [*kafka_broker-env, *stage-quorum-voters]

      CLUSTER_ID: ${CLUSTER_ID_STAGE}
      KAFKA_NODE_ID: ${SB_2_NODE_ID}
      KAFKA_LISTENERS: BROKER://:${SB_2_PORT_90},INTERNAL://:${SB_2_PORT_92}
      KAFKA_ADVERTISED_LISTENERS: BROKER://localhost:${SB_2_PORT_90},INTERNAL://${SB_2_NAME}:${SB_2_PORT_92}

    volumes:
      - ./etc-kafka-secrets:/etc/kafka/secrets
      - ${SB_2_NAME}_data:/var/lib/kafka/data
    networks:
      - ${STAGE_CLUSTER_NETWORK}
    <<: *broker-entrypoint-with-secrets
    deploy:
      <<: *broker-resources

  # stage broker 3/3
  stage-broker-3:
    image: ${IMAGE}
    container_name: ${SB_3_NAME}
    hostname: ${SB_3_NAME}
    env_file:
      - ${ENV_PATH:-.env}
    ports:
      - ${SB_3_PORT_90}:${SB_3_PORT_90}
      - ${SB_3_PORT_91}:${SB_3_PORT_91}
    environment:
      <<: [*kafka_broker-env, *stage-quorum-voters]

      CLUSTER_ID: ${CLUSTER_ID_STAGE}
      KAFKA_NODE_ID: ${SB_3_NODE_ID}
      KAFKA_LISTENERS: BROKER://:${SB_3_PORT_90},INTERNAL://:${SB_3_PORT_92}
      KAFKA_ADVERTISED_LISTENERS: BROKER://localhost:${SB_3_PORT_90},INTERNAL://${SB_3_NAME}:${SB_3_PORT_92}

    volumes:
      - ./etc-kafka-secrets:/etc/kafka/secrets
      - ${SB_3_NAME}_data:/var/lib/kafka/data
    networks:
      - ${STAGE_CLUSTER_NETWORK}
    <<: *broker-entrypoint-with-secrets
    deploy:
      <<: *broker-resources

  # kafka mart cluster: KRaft, 3 controllers, 3 brokers

  # mart cluster controllers

  # mart controller 1/3
  mart-controller-1:
    image: ${IMAGE}
    container_name: ${MC_1_NAME}
    hostname: ${MC_1_NAME}
    env_file:
      - ${ENV_PATH:-.env}
    ports:
      - ${MC_1_PORT_90}:${MC_1_PORT_90}
      - ${MC_1_PORT_91}:${MC_1_PORT_91}
    environment:
      <<: [*kafka_controller-env, *mart-quorum-voters]

      CLUSTER_ID: ${CLUSTER_ID_MART}
      KAFKA_NODE_ID: ${MC_1_NODE_ID}
      KAFKA_LISTENERS: CONTROLLER://:${MC_1_PORT_90}

    volumes:
      - ./etc-kafka-secrets:/etc/kafka/secrets
      - ${MC_1_NAME}_data:/var/lib/kafka/data
    networks:
      - ${MART_CLUSTER_NETWORK}
    <<: *controller-entrypoint-with-secrets
    deploy:
      <<: *controller-resources

  # mart controller 2/3
  mart-controller-2:
    image: ${IMAGE}
    container_name: ${MC_2_NAME}
    hostname: ${MC_2_NAME}
    env_file:
      - ${ENV_PATH:-.env}
    ports:
      - ${MC_2_PORT_90}:${MC_2_PORT_90}
      - ${MC_2_PORT_91}:${MC_2_PORT_91}
    environment:
      <<: [*kafka_controller-env, *mart-quorum-voters]

      CLUSTER_ID: ${CLUSTER_ID_MART}
      KAFKA_NODE_ID: ${MC_2_NODE_ID}
      KAFKA_LISTENERS: CONTROLLER://:${MC_2_PORT_90}

    volumes:
      - ./etc-kafka-secrets:/etc/kafka/secrets
      - ${MC_2_NAME}_data:/var/lib/kafka/data
    networks:
      - ${MART_CLUSTER_NETWORK}
    <<: *controller-entrypoint-with-secrets
    deploy:
      <<: *controller-resources

  # mart controller 3/3
  mart-controller-3:
    image: ${IMAGE}
    container_name: ${MC_3_NAME}
    hostname: ${MC_3_NAME}
    env_file:
      - ${ENV_PATH:-.env}
    ports:
      - ${MC_3_PORT_90}:${MC_3_PORT_90}
      - ${MC_3_PORT_91}:${MC_3_PORT_91}
    environment:
      <<: [*kafka_controller-env, *mart-quorum-voters]

      CLUSTER_ID: ${CLUSTER_ID_MART}
      KAFKA_NODE_ID: ${MC_3_NODE_ID}
      KAFKA_LISTENERS: CONTROLLER://:${MC_3_PORT_90}

    volumes:
      - ./etc-kafka-secrets:/etc/kafka/secrets
      - ${MC_3_NAME}_data:/var/lib/kafka/data
    networks:
      - ${MART_CLUSTER_NETWORK}
    <<: *controller-entrypoint-with-secrets
    deploy:
      <<: *controller-resources

  # mart cluster brokers

  # mart broker 1/3
  mart-broker-1:
    image: ${IMAGE}
    container_name: ${MB_1_NAME}
    hostname: ${MB_1_NAME}
    env_file:
      - ${ENV_PATH:-.env}
    ports:
      - ${MB_1_PORT_90}:${MB_1_PORT_90}
      - ${MB_1_PORT_91}:${MB_1_PORT_91}
    environment:
      <<: [*kafka_broker-env, *mart-quorum-voters]

      CLUSTER_ID: ${CLUSTER_ID_MART}
      KAFKA_NODE_ID: ${MB_1_NODE_ID}
      KAFKA_LISTENERS: BROKER://:${MB_1_PORT_90},INTERNAL://:${MB_1_PORT_92}
      KAFKA_ADVERTISED_LISTENERS: BROKER://localhost:${MB_1_PORT_90},INTERNAL://${MB_1_NAME}:${MB_1_PORT_92}

    volumes:
      - ./etc-kafka-secrets:/etc/kafka/secrets
      - ${MB_1_NAME}_data:/var/lib/kafka/data
    networks:
      - ${MART_CLUSTER_NETWORK}
    <<: *broker-entrypoint-with-secrets
    deploy:
      <<: *broker-resources

  # mart broker 2/3
  mart-broker-2:
    image: ${IMAGE}
    container_name: ${MB_2_NAME}
    hostname: ${MB_2_NAME}
    env_file:
      - ${ENV_PATH:-.env}
    ports:
      - ${MB_2_PORT_90}:${MB_2_PORT_90}
      - ${MB_2_PORT_91}:${MB_2_PORT_91}
    environment:
      <<: [*kafka_broker-env, *mart-quorum-voters]

      CLUSTER_ID: ${CLUSTER_ID_MART}
      KAFKA_NODE_ID: ${MB_2_NODE_ID}
      KAFKA_LISTENERS: BROKER://:${MB_2_PORT_90},INTERNAL://:${MB_2_PORT_92}
      KAFKA_ADVERTISED_LISTENERS: BROKER://localhost:${MB_2_PORT_90},INTERNAL://${MB_2_NAME}:${MB_2_PORT_92}

    volumes:
      - ./etc-kafka-secrets:/etc/kafka/secrets
      - ${MB_2_NAME}_data:/var/lib/kafka/data
    networks:
      - ${MART_CLUSTER_NETWORK}
    <<: *broker-entrypoint-with-secrets
    deploy:
      <<: *broker-resources

  # mart broker 3/3
  mart-broker-3:
    image: ${IMAGE}
    container_name: ${MB_3_NAME}
    hostname: ${MB_3_NAME}
    env_file:
      - ${ENV_PATH:-.env}
    ports:
      - ${MB_3_PORT_90}:${MB_3_PORT_90}
      - ${MB_3_PORT_91}:${MB_3_PORT_91}
    environment:
      <<: [*kafka_broker-env, *mart-quorum-voters]

      CLUSTER_ID: ${CLUSTER_ID_MART}
      KAFKA_NODE_ID: ${MB_3_NODE_ID}
      KAFKA_LISTENERS: BROKER://:${MB_3_PORT_90},INTERNAL://:${MB_3_PORT_92}
      KAFKA_ADVERTISED_LISTENERS: BROKER://localhost:${MB_3_PORT_90},INTERNAL://${MB_3_NAME}:${MB_3_PORT_92}

    volumes:
      - ./etc-kafka-secrets:/etc/kafka/secrets
      - ${MB_3_NAME}_data:/var/lib/kafka/data
    networks:
      - ${MART_CLUSTER_NETWORK}
    <<: *broker-entrypoint-with-secrets
    deploy:
      <<: *broker-resources

  # topic-creation
  topic-creation:
    image: ${IMAGE}
    container_name: ${SERVICE_TOPIC_CREATOR_NAME}
    hostname: ${SERVICE_TOPIC_CREATOR_NAME}
    env_file:
      - ${ENV_PATH:-.env}
    depends_on:
      - ${SC_1_NAME}
      - ${SC_2_NAME}
      - ${SC_3_NAME}
      - ${SB_1_NAME}
      - ${SB_2_NAME}
      - ${SB_3_NAME}
      - ${MC_1_NAME}
      - ${MC_2_NAME}
      - ${MC_3_NAME}
      - ${MB_1_NAME}
      - ${MB_2_NAME}
      - ${MB_3_NAME}
    command: >
      bash -c "
          sleep 20 &&
          chmod +x /etc/kafka/secrets/setup-acls-stage.sh &&
          /etc/kafka/secrets/setup-acls-stage.sh &&
          chmod +x /etc/kafka/secrets/setup-acls-mart.sh &&
          /etc/kafka/secrets/setup-acls-mart.sh &&
          sleep 20"
    volumes:
      - ./etc-kafka-secrets:/etc/kafka/secrets
      - ${SERVICE_TOPIC_CREATOR_NAME}_data:/var/lib/kafka/data
    networks:
      - ${STAGE_CLUSTER_NETWORK}
      - ${MART_CLUSTER_NETWORK}
    deploy:
      resources:
        limits:
          # cpus: '${SERVICE_TOPIC_CREATOR_LIMIT_CPUS}'
          memory: ${SERVICE_TOPIC_CREATOR_LIMIT_MEMORY}
        reservations:
          cpus: '${SERVICE_TOPIC_CREATOR_RESERVE_CPUS}'
          memory: ${SERVICE_TOPIC_CREATOR_RESERVE_MEMORY}

  # schema-registry
  schema-registry:
    image: ${IMAGE_SCHEMA_REGISTRY}
    container_name: ${SERVICE_SCHEMA_REGISTRY_NAME}
    hostname: ${SERVICE_SCHEMA_REGISTRY_NAME}
    env_file:
      - ${ENV_PATH:-.env}
    depends_on:
      topic-creation:
        condition: service_completed_successfully
    ports:
      - "${SERVICE_SCHEMA_REGISTRY_REST_PORT_EXPOSE}:${SERVICE_SCHEMA_REGISTRY_REST_PORT}"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: ${SERVICE_SCHEMA_REGISTRY_NAME}
      ## _schemas - дефалтное значение;
      ## мы будем создавать топик и ACL-ы вручную (в сервисе topic-creation),
      ## чтобы не давать неограниченные права реестру (см. README.md)
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: "${SERVICE_SCHEMA_REGISTRY_KAFKASTORE_TOPIC}"
      SCHEMA_REGISTRY_KAFKASTORE_GROUP_ID: "${SERVICE_SCHEMA_REGISTRY_KAFKASTORE_GROUP_ID}"
      SCHEMA_REGISTRY_SCHEMA_REGISTRY_GROUP_ID: "${SERVICE_SCHEMA_REGISTRY_KAFKASTORE_GROUP_ID}"
      # транзакционность и идемпотентность вообще не включаются никак, три дня убил на РнД (((
      #SCHEMA_REGISTRY_KAFKASTORE_TRANSACTIONAL_ID: "${SERVICE_SCHEMA_REGISTRY_KAFKASTORE_TRANSACTIONAL_ID}"
      ## фактор репликации <= количеству брокеров
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 3
      ## ВСЕГДА должна быть 1-ца (а политика - COMPACT, это учесть в topic-creation)
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_PARTITION_COUNT: 1
      #SCHEMA_REGISTRY_KAFKASTORE_MAX_RETRIES: "20"
      SCHEMA_REGISTRY_KAFKASTORE_ACK_ALL: "true"
      #SCHEMA_REGISTRY_KAFKASTORE_ENABLE_IDEMPOTENCE: "true"
      #SCHEMA_REGISTRY_KAFKASTORE_EXTRA_CONFIG: "enable.idempotence=true"
      #SCHEMA_REGISTRY_KAFKASTORE_PRODUCER_ENABLE_IDEMPOTENCE: "true"
      #SCHEMA_REGISTRY_OPTS: "-Dkafkastore.enable.idempotence=true"
      SCHEMA_REGISTRY_DEBUG: true
      #SCHEMA_REGISTRY_KAFKASTORE_ISOLATION_LEVEL: "read_committed"
      #SCHEMA_REGISTRY_MASTER_ELIGIBILITY: "true"
      #SCHEMA_REGISTRY_KAFAKSTORE_GROUP_ID: "${SERVICE_SCHEMA_REGISTRY_KAFKASTORE_GROUP_ID}"
      #SCHEMA_REGISTRY_ELECTION_TYPE: "none"

      #SCHEMA_REGISTRY_KAFKASTORE_INIT_TIMEOUT_MS: "90000"
      #SCHEMA_REGISTRY_KAFKASTORE_WRITE_RETRY_BACKOFF_MS: "2000"
      #SCHEMA_REGISTRY_KAFKASTORE_TIMEOUT_MS: "90000"
      #SCHEMA_REGISTRY_KAFKASTORE_RETRY_BACKOFF_MS: "2000"
      #SCHEMA_REGISTRY_KAFKASTORE_MAX_BLOCK_MS: "60000"

      # https
      SCHEMA_REGISTRY_LISTENERS: https://0.0.0.0:${SERVICE_SCHEMA_REGISTRY_REST_PORT}
      # HTTPS для связи между нодами
      # (их сейчас нет у schema-registry,
      # но надо явно указать то же, что в SCHEMA_REGISTRY_LISTENERS)
      SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: "https"
      # полезно для HTTPS:
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: GET,POST,PUT,OPTIONS
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: "*"

      # Настройки SSL (mTLS) для самого Schema Registry (Server Side)
      SCHEMA_REGISTRY_SSL_TRUSTSTORE_TYPE: "${TRUSTSTORE_TYPE}"
      SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION: ${CONTAINER_PATH_TRUSTSTORE}
      SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD: ${KAFKA_TRUSTSTORE_CREDS}
      SCHEMA_REGISTRY_SSL_KEYSTORE_TYPE: "${KEYSTORE_TYPE}"
      SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION: ${CONTAINER_PATH_KEYSTORE}
      SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD: ${KAFKA_KEYSTORE_CREDS}
      SCHEMA_REGISTRY_SSL_KEY_PASSWORD: ${KAFKA_SSLKEY_CREDS}
      # Jetty хочет true/false, не required/none
      SCHEMA_REGISTRY_SSL_CLIENT_AUTH: "true" # "required" # "none|required": TLS|mTLS

      # Настройки для связи с Kafka (Client Side)
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'SASL_SSL://${SB_1_NAME}:${SB_1_PORT_92},SASL_SSL://${SB_2_NAME}:${SB_2_PORT_92},SASL_SSL://${SB_3_NAME}:${SB_3_PORT_92}'
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SASL_SSL
      SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM: PLAIN
      SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username='${SASL_UNAME_SCHEMA_REGISTRY}' password='${SASL_PWD_SCHEMA_REGISTRY}';"
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_TYPE: "${TRUSTSTORE_TYPE}"
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_LOCATION: ${CONTAINER_PATH_TRUSTSTORE}
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_PASSWORD: ${KAFKA_TRUSTSTORE_CREDS}
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_TYPE: "${KEYSTORE_TYPE}"
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_LOCATION: ${CONTAINER_PATH_KEYSTORE}
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_PASSWORD: ${KAFKA_KEYSTORE_CREDS}
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEY_PASSWORD: ${KAFKA_SSLKEY_CREDS}
      SCHEMA_REGISTRY_KAFKASTORE_SSL_CLIENT_AUTH: "required" # "none|required": TLS|mTLS

      # memory limits percentage
      SCHEMA_REGISTRY_HEAP_OPTS: "${SERVICE_SCHEMA_REGISTRY_HEAP_OPTS}"
    # command: /bin/sh -c "schema-registry-start /etc/schema-registry/schema-registry.properties"
    volumes:
      - ./etc-kafka-secrets:/etc/kafka/secrets
      # - ./schema-registry.properties:/etc/schema-registry/schema-registry.properties
      # - ...:/var/log/schema-registry
    networks:
      - ${STAGE_CLUSTER_NETWORK}
    deploy:
      resources:
        limits:
          # cpus: '${SERVICE_SCHEMA_REGISTRY_LIMIT_CPUS}'
          memory: ${SERVICE_SCHEMA_REGISTRY_LIMIT_MEMORY}
        reservations:
          cpus: '${SERVICE_SCHEMA_REGISTRY_RESERVE_CPUS}'
          memory: ${SERVICE_SCHEMA_REGISTRY_RESERVE_MEMORY}
    # entrypoint: ["tail", "-f", "/dev/null"]

  # schemas-registrator
  schemas-registrator:
    image: ${IMAGE}
    container_name: ${SERVICE_SCHEMAS_REGISTRATOR_NAME}
    hostname: ${SERVICE_SCHEMAS_REGISTRATOR_NAME}
    env_file:
      - ${ENV_PATH:-.env}
    depends_on:
      - ${SERVICE_SCHEMA_REGISTRY_NAME}
    command: >
      bash -c "
          sleep 20 &&
          echo 'Ждём готовности Schema Registry на ${SCHEMA_REGISTRY_REST_URL_INNER}...' &&
          until curl -k -s -f --cert-type P12 --cert '${CONTAINER_PATH_KEYSTORE}:${KAFKA_KEYSTORE_CREDS}' '${SCHEMA_REGISTRY_REST_URL_INNER}/subjects'  > /dev/null; do
            echo 'Schema Registry ещё не доступен, ждём 2 секунды...' &&
            sleep 2;
          done &&
          chmod +x /etc/kafka/secrets/setup-schemas.sh &&
          /etc/kafka/secrets/setup-schemas.sh"
    volumes:
      - ./etc-kafka-secrets:/etc/kafka/secrets
      - ${SERVICE_SCHEMAS_REGISTRATOR_NAME}_data:/var/lib/kafka/data
    networks:
      - ${STAGE_CLUSTER_NETWORK}
    deploy:
      resources:
        limits:
          # cpus: '${SERVICE_SCHEMAS_REGISTRATOR_LIMIT_CPUS}'
          memory: ${SERVICE_SCHEMAS_REGISTRATOR_LIMIT_MEMORY}
        reservations:
          cpus: '${SERVICE_SCHEMAS_REGISTRATOR_RESERVE_CPUS}'
          memory: ${SERVICE_SCHEMAS_REGISTRATOR_RESERVE_MEMORY}

  # mirror-maker
  mirror-maker:
    image: ${IMAGE}
    container_name: ${SERVICE_MIRROR_MAKER_NAME}
    hostname: ${SERVICE_MIRROR_MAKER_NAME}
    env_file:
      - ${ENV_PATH:-.env}
    depends_on:
      schemas-registrator:
        condition: service_completed_successfully
    command: >
      bash -c "
          echo 'bootstrap.servers=${SB_1_NAME}:${SB_1_PORT_92}' > /tmp/consumer.properties &&
          echo 'group.id=mirror-maker-group' >> /tmp/consumer.properties &&
          echo 'key.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer' >> /tmp/consumer.properties &&
          echo 'value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer' >> /tmp/consumer.properties &&
          echo 'security.protocol=SASL_SSL' >> /tmp/consumer.properties &&
          echo 'sasl.mechanism=PLAIN' >> /tmp/consumer.properties &&
          echo 'sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${SASL_UNAME_ADMIN}" password="${SASL_PWD_ADMIN}";' >> /tmp/consumer.properties &&
          echo 'ssl.truststore.location=${CONTAINER_PATH_TRUSTSTORE}' >> /tmp/consumer.properties &&
          echo 'ssl.truststore.password=${KAFKA_TRUSTSTORE_CREDS}' >> /tmp/consumer.properties &&
          echo 'ssl.keystore.location=${CONTAINER_PATH_KEYSTORE}' >> /tmp/consumer.properties &&
          echo 'ssl.keystore.password=${KAFKA_KEYSTORE_CREDS}' >> /tmp/consumer.properties &&
          echo 'ssl.key.password=${KAFKA_SSLKEY_CREDS}' >> /tmp/consumer.properties &&

          echo 'bootstrap.servers=${MB_1_NAME}:${MB_1_PORT_92}' > /tmp/producer.properties &&
          echo 'key.serializer=org.apache.kafka.common.serialization.ByteArraySerializer' >> /tmp/producer.properties &&
          echo 'value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer' >> /tmp/producer.properties &&
          echo 'security.protocol=SASL_SSL' >> /tmp/producer.properties &&
          echo 'sasl.mechanism=PLAIN' >> /tmp/producer.properties &&
          echo 'sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${SASL_UNAME_ADMIN}" password="${SASL_PWD_ADMIN}";' >> /tmp/producer.properties &&
          echo 'ssl.truststore.location=${CONTAINER_PATH_TRUSTSTORE}' >> /tmp/producer.properties &&
          echo 'ssl.truststore.password=${KAFKA_TRUSTSTORE_CREDS}' >> /tmp/producer.properties &&
          echo 'ssl.keystore.location=${CONTAINER_PATH_KEYSTORE}' >> /tmp/producer.properties &&
          echo 'ssl.keystore.password=${KAFKA_KEYSTORE_CREDS}' >> /tmp/producer.properties &&
          echo 'ssl.key.password=${KAFKA_SSLKEY_CREDS}' >> /tmp/producer.properties &&

          kafka-mirror-maker --consumer.config /tmp/consumer.properties --producer.config /tmp/producer.properties --whitelist ${TOPIC_GOODS_FILTERED} --num.streams 1"
    volumes:
      - ./etc-kafka-secrets:/etc/kafka/secrets
      - ${SERVICE_MIRROR_MAKER_NAME}_data:/var/lib/kafka/data
      # я так понимаю - чисто почитать, что мы там написали в command (?)
      # - ./mirror-maker-consumer.cfg:/tmp/consumer.properties
      # - ./mirror-maker-producer.cfg:/tmp/producer.properties
    networks:
      - ${STAGE_CLUSTER_NETWORK}
      - ${MART_CLUSTER_NETWORK}
    deploy:
      resources:
        limits:
          # cpus: '${SERVICE_MIRROR_MAKER_LIMIT_CPUS}'
          memory: ${SERVICE_MIRROR_MAKER_LIMIT_MEMORY}
        reservations:
          cpus: '${SERVICE_MIRROR_MAKER_RESERVE_CPUS}'
          memory: ${SERVICE_MIRROR_MAKER_RESERVE_MEMORY}

  # kafka-ui
  kafka-ui:
    image: ${IMAGE_PROVECTUSLABS_KAFKA_UI}
    container_name: ${SERVICE_KAFKA_UI_NAME}
    hostname: ${SERVICE_KAFKA_UI_NAME}
    env_file:
      - ${ENV_PATH:-.env}
    depends_on:
      schemas-registrator:
        condition: service_completed_successfully
    ports:
      - "${SERVICE_KAFKA_UI_PORT_80}:8080"
    environment:
      ## Вместо KAFKA_OPTS используем JAVA_OPTS
      JAVA_OPTS:  "-Djava.security.auth.login.config=/etc/kafka/secrets/kafkaui.sasl.jaas.conf"
      KAFKA_CLUSTERS_0_NAME: stage
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${SB_1_NAME}:${SB_1_PORT_92},${SB_2_NAME}:${SB_2_PORT_92},${SB_3_NAME}:${SB_3_PORT_92}
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
      # KAFKA_CLUSTERS_0_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_SECRETS_DIR: /etc/kafka/secrets
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION: ${CONTAINER_PATH_TRUSTSTORE}
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_TYPE: ${KEYSTORE_TYPE}
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION: ${CONTAINER_PATH_KEYSTORE}
      # креды указываем через _PASSWORD, через _CREDENTIALS не хочет
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: ${KAFKA_TRUSTSTORE_CREDS}
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD: ${KAFKA_KEYSTORE_CREDS}
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEY_PASSWORD: ${KAFKA_SSLKEY_CREDS}
      KAFKA_CLUSTERS_1_NAME: mart
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: ${MB_1_NAME}:${MB_1_PORT_92},${MB_2_NAME}:${MB_2_PORT_92},${MB_3_NAME}:${MB_3_PORT_92}
      KAFKA_CLUSTERS_1_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
      # KAFKA_CLUSTERS_1_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      KAFKA_CLUSTERS_1_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_SECRETS_DIR: /etc/kafka/secrets
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_TRUSTSTORE_LOCATION: ${CONTAINER_PATH_TRUSTSTORE}
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_KEYSTORE_TYPE: ${KEYSTORE_TYPE}
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_KEYSTORE_LOCATION: ${CONTAINER_PATH_KEYSTORE}
      # креды указываем через _PASSWORD, через _CREDENTIALS не хочет
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: ${KAFKA_TRUSTSTORE_CREDS}
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_KEYSTORE_PASSWORD: ${KAFKA_KEYSTORE_CREDS}
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_KEY_PASSWORD: ${KAFKA_SSLKEY_CREDS}
    volumes:
      - ./etc-kafka-secrets:/etc/kafka/secrets
    networks:
      - ${STAGE_CLUSTER_NETWORK}
      - ${MART_CLUSTER_NETWORK}
    # root нужен, чтобы записать файлы
    # (далее ставится владельцем kafkaui (1001) и идёт запуск приложения от kafkaui)
    user: root
    entrypoint:
      - /bin/sh
      - -c
      - |
        mkdir -p /etc/kafka/secrets
        cat <<EOF > /etc/kafka/secrets/kafkaui.sasl.jaas.conf
        KafkaClient {
            org.apache.kafka.common.security.plain.PlainLoginModule required
            username="${SASL_UNAME_KAFKA_UI}"
            password="${SASL_PWD_KAFKA_UI}";
        };
        EOF
        
        # Права для пользователя 1001 (kafkaui в Alpine)
        # chown 1001 + chmod 600 - не надо,
        # надо без chown и chmod 664
        # (возможно потому, что мы в vulume на одну и ту же диру
        # хостовой машины, но на два образа с двумя разными юзерами,
        # от которых приложение в контейнере зпускается)
        # chown -R 1001:1001 /etc/kafka/secrets
        # chmod 600 /etc/kafka/secrets/kafkaui.sasl.jaas.conf
        chmod 664 /etc/kafka/secrets/kafkaui.sasl.jaas.conf
        
        echo "JAAS for Kafka UI generated from .env"
        # Запуск через su для понижения привилегий до kafkaui
        exec su kafkaui -s /bin/sh -c 'java $$JAVA_OPTS --add-opens java.rmi/javax.rmi.ssl=ALL-UNNAMED -jar kafka-ui-api.jar'
    deploy:
      resources:
        limits:
          # cpus: '${SERVICE_KAFKA_UI_LIMIT_CPUS}'
          memory: ${SERVICE_KAFKA_UI_LIMIT_MEMORY}
        reservations:
          cpus: '${SERVICE_KAFKA_UI_RESERVE_CPUS}'
          memory: ${SERVICE_KAFKA_UI_RESERVE_MEMORY}

  kafka-connect:
    container_name: ${SERVICE_KAFKA_CONNECT_NAME}
    hostname: ${SERVICE_KAFKA_CONNECT_NAME}
    env_file:
      - ${ENV_PATH:-.env}
    depends_on:
      schemas-registrator:
        condition: service_completed_successfully
      mirror-maker:
        condition: service_started
      # - schema-registry
    build:
      context: ./kafka-connect
      args:
        - IMAGE_KAFKA_CONNECT=${IMAGE_KAFKA_CONNECT}
    ports:
      # REST API Kafka Connect
      - "${SERVICE_KAFKA_CONNECT_REST_PORT_EXPOSE}:${SERVICE_KAFKA_CONNECT_REST_PORT}"
      # JMX for Prometheus: 9875, 9876
      # - "9875:9875"
      # - "9876:9876"
    deploy:
      resources:
        limits:
          # cpus: '${SERVICE_KAFKA_CONNECT_LIMIT_CPUS}'
          memory: ${SERVICE_KAFKA_CONNECT_LIMIT_MEMORY}
        reservations:
          cpus: '${SERVICE_KAFKA_CONNECT_RESERVE_CPUS}'
          memory: ${SERVICE_KAFKA_CONNECT_RESERVE_MEMORY}
    volumes:
      - ./etc-kafka-secrets:/etc/kafka/secrets
      - ./kafka-connect/data/shop_api_stage:/data/shop_api_stage
      - ./kafka-connect/data/shop_api_error:/data/shop_api_error
    networks:
      - ${STAGE_CLUSTER_NETWORK}
    environment:
      CONNECT_BOOTSTRAP_SERVERS: ${SB_1_NAME}:${SB_1_PORT_92},${SB_2_NAME}:${SB_2_PORT_92},${SB_3_NAME}:${SB_3_PORT_92}
      CONNECT_GROUP_ID: '${SERVICE_KAFKA_CONNECT_NAME}'
      CONNECT_REST_PORT: ${SERVICE_KAFKA_CONNECT_REST_PORT}

      CONNECT_REST_ADVERTISED_HOST_NAME: '${SERVICE_KAFKA_CONNECT_NAME}'
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"

      CONNECT_CONFIG_STORAGE_TOPIC: "${TOPIC_CONNECT_CONFIG_STORAGE}"
      CONNECT_OFFSET_STORAGE_TOPIC: "${TOPIC_CONNECT_OFFSET_STORAGE}"
      CONNECT_STATUS_STORAGE_TOPIC: "${TOPIC_CONNECT_STATUS_STORAGE}"

      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 3

      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      # deprecated: CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      # deprecated: CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      # deprecated: CONNECT_INTERNAL_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"

      # Настройки SSL/SASL для подключения к брокерам под connect_user
      CONNECT_SECURITY_PROTOCOL: "SASL_SSL"
      CONNECT_SASL_MECHANISM: "PLAIN"
      CONNECT_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="${SASL_UNAME_KAFKA_CONNECT}" password="${SASL_PWD_KAFKA_CONNECT}";'

      CONNECT_SSL_TRUSTSTORE_LOCATION: ${CONTAINER_PATH_TRUSTSTORE}
      CONNECT_SSL_TRUSTSTORE_PASSWORD: ${KAFKA_TRUSTSTORE_CREDS}
      CONNECT_SSL_KEYSTORE_TYPE: ${KEYSTORE_TYPE}
      CONNECT_SSL_KEYSTORE_LOCATION: ${CONTAINER_PATH_KEYSTORE}
      CONNECT_SSL_KEYSTORE_PASSWORD: ${KAFKA_KEYSTORE_CREDS}
      CONNECT_SSL_KEY_PASSWORD: ${KAFKA_SSLKEY_CREDS}

      # Настройки SSL/SASL для подключения к брокерам под connect_user
      CONNECT_PRODUCER_SECURITY_PROTOCOL: "SASL_SSL"
      CONNECT_PRODUCER_SASL_MECHANISM: "PLAIN"
      CONNECT_PRODUCER_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="${SASL_UNAME_KAFKA_CONNECT}" password="${SASL_PWD_KAFKA_CONNECT}";'
      
      CONNECT_PRODUCER_SSL_TRUSTSTORE_LOCATION: ${CONTAINER_PATH_TRUSTSTORE}
      CONNECT_PRODUCER_SSL_TRUSTSTORE_PASSWORD: ${KAFKA_TRUSTSTORE_CREDS}
      CONNECT_PRODUCER_SSL_KEYSTORE_TYPE: ${KEYSTORE_TYPE}
      CONNECT_PRODUCER_SSL_KEYSTORE_LOCATION: ${CONTAINER_PATH_KEYSTORE}
      CONNECT_PRODUCER_SSL_KEYSTORE_PASSWORD: ${KAFKA_KEYSTORE_CREDS}
      CONNECT_PRODUCER_SSL_KEY_PASSWORD: ${KAFKA_SSLKEY_CREDS}

      CONNECT_PLUGIN_DISCOVERY: "only_scan"

      # согласоввывай с SERVICE_KAFKA_CONNECT_LIMIT_MEMORY, etc.
      KAFKA_HEAP_OPTS: "${SERVICE_KAFKA_CONNECT_HEAP_OPTS}"

      # Export JMX metrics to :9876/metrics for Prometheus
      # KAFKA_JMX_PORT: '9875'
      # KAFKA_OPTS: "-javaagent:/opt/jmx_prometheus_javaagent-0.15.0.jar=9876:/opt/kafka-connect.yml"

#  shop-api-app:
#    build:
#      context: ./shop-api-app
#    container_name: ${SERVICE_SHOP_API_APP_NAME}
#    hostname: ${SERVICE_SHOP_API_APP_NAME}
#    env_file:
#      - ${ENV_PATH:-.env}
#    depends_on:
#      - ${SERVICE_KAFKA_CONNECT_NAME}
#    ports:
#      - "6066-6077:6066-6077"
#    volumes:
#      - shop_api_app:/app
#      - ./etc-kafka-secrets:/etc/kafka/secrets
#    stdin_open: true
#    tty: true
#    networks:
#      - ${STAGE_CLUSTER_NETWORK}

networks:
  ya-kafka-pf-stage:
    name: ${STAGE_CLUSTER_NETWORK}_network
  ya-kafka-pf-mart:
    name: ${MART_CLUSTER_NETWORK}_network

volumes:
  stage-controller-1_data:
  stage-controller-2_data:
  stage-controller-3_data:
  stage-broker-1_data:
  stage-broker-2_data:
  stage-broker-3_data:
  mart-controller-1_data:
  mart-controller-2_data:
  mart-controller-3_data:
  mart-broker-1_data:
  mart-broker-2_data:
  mart-broker-3_data:
  topic-creation_data:
  schemas-registrator_data:
  mirror-maker_data:
  shop_api_app:
