kafkastore.acks=all
kafkastore.retries=2147483647
kafkastore.max.in.flight.requests.per.connection=5
kafkastore.enable.idempotence=true
kafkastore.producer.acks=all
kafkastore.producer.retries=2147483647
kafkastore.producer.max.in.flight.requests.per.connection=5
kafkastore.producer.enable.idempotence=true
kafkastore.kafkastore.enable.idempotence=true
